format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  myql:                                             # name of the pipeline job that will be showing on UI
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/B58-CloudDevOps/ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    stages:                                       
      - dev:                                        # Name of the stage 
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false 
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh

      - qa:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh

      - stage:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh

      - prod:
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false 
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh